data_ingestion:
  input_path: "/data2/experiment-tracking/mlflow-demo/data/raw"
  output_path: "/data2/experiment-tracking/mlflow-demo/data/ingested"

data_transformation:
  input_path: "/data2/experiment-tracking/mlflow-demo/data/ingested"
  output_path: "/data2/experiment-tracking/mlflow-demo/data/preprocessed"

train: 
  input_path: "/data2/experiment-tracking/mlflow-demo/data/preprocessed"
  output_path: "/data2/experiment-tracking/mlflow-demo/data/train"
  