data_ingestion:
  input_path: "data/raw"
  output_path: "data/ingested"

data_transformation:
  input_path: "data/ingested"
  output_path: "data/preprocessed"

train: 
  input_path: "data/preprocessed"
  output_path: "data/train"
  